### ISSUE TITLE
Supervisor stdout compatibility iss with Python3.6.8 version

### ISSUE THREAD

**Issue by AnandPalani92** [coderanger/supervisor-stdout#19]
I used python3.6.8 version on our application and i have used supervisor-stdout pip package on our docker image. when i start the container and got the below error on the docker logs
Traceback (most recent call last):
  File "/usr/local/bin/supervisord", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/supervisor/supervisord.py", line 354, in main
    options.realize(args, doc=__doc__)
  File "/usr/local/lib/python3.6/site-packages/supervisor/options.py", line 484, in realize
    Options.realize(self, *arg, **kw)
  File "/usr/local/lib/python3.6/site-packages/supervisor/options.py", line 308, in realize
    self.process_config()
  File "/usr/local/lib/python3.6/site-packages/supervisor/options.py", line 544, in process_config
    Options.process_config(self, do_usage=do_usage)
  File "/usr/local/lib/python3.6/site-packages/supervisor/options.py", line 316, in process_config
    self.process_config_file(do_usage)
  File "/usr/local/lib/python3.6/site-packages/supervisor/options.py", line 346, in process_config_file
    self.read_config(self.configfile)
  File "/usr/local/lib/python3.6/site-packages/supervisor/options.py", line 661, in read_config
    section.process_group_configs = self.process_groups_from_parser(parser)
  File "/usr/local/lib/python3.6/site-packages/supervisor/options.py", line 742, in process_groups_from_parser
    result_handler = self.import_spec(result_handler)
  File "/usr/local/lib/python3.6/site-packages/supervisor/options.py", line 391, in import_spec
    return ep.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/supervisor_stdout.py", line 22
    print '%s %s | %s'%(headers['processname'], headers['channel'], data),
                     ^
SyntaxError: invalid syntax

I have configured the supervisor.conf as per your suggestion, kindly check and resolve the issue

**Comment by mrdoug47** [comment]
I'm having this issue as well when running ubuntu 20 containers, back-leveling to ubuntu 18 resolved my problems

**Comment by orangepeelbeef** [comment]
This specific error is fixed in the repository, but the pypi package hasn't been updated, so you can install via:

pip install git+https://github.com/coderanger/supervisor-stdout

**Comment by markeissler** [comment]
More accurately, the actual command is:

```bash
pip install 'supervisor-stdout @ git+https://github.com/coderanger/supervisor-stdout'
```

- or -

```bash
pip install git+https://github.com/coderanger/supervisor-stdout
```

**Comment by dupegui334** [comment]
@coderanger do you know if the pypi package `supervisor-stdout 0.1.1` will be updated with the fix? it would be really helpful, because using something like `pip-compile --generate-hashes` does not work for generating the hashes of packages that are referenced like this `git+https://github.com/coderanger/supervisor-stdout`.
